In [131]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings("ignore")

## Q1(MNIST)

In [132]:
import torch
(x_train, y_train, x_test, y_test)=torch.load('mnist.pt')

In [133]:
x_train.shape

torch.Size([1000, 28, 28])

In [134]:
for i in range(10):
    print( y_train[i])

tensor(5, dtype=torch.uint8)
tensor(0, dtype=torch.uint8)
tensor(4, dtype=torch.uint8)
tensor(1, dtype=torch.uint8)
tensor(9, dtype=torch.uint8)
tensor(2, dtype=torch.uint8)
tensor(1, dtype=torch.uint8)
tensor(3, dtype=torch.uint8)
tensor(1, dtype=torch.uint8)
tensor(4, dtype=torch.uint8)


In [135]:
#reshaping the dataset
x_train=x_train.reshape((1000,28*28))
x_test=x_test.reshape((100,28*28))

In [136]:
#defining KNN function and printing confusion matrix and  accuracy results
def KNN(n,x_train, y_train,x_test,y_test):
    clf = KNeighborsClassifier(n_neighbors=n)
    clf.fit(x_train, y_train)
    y_pred=clf.predict(x_test)
    print('Confusion Matrix of the given KNN classification with K =',n)
    print()
    print(confusion_matrix(y_test, y_pred))
    print('\nAccuracy of the above classification is ',accuracy_score(y_test, y_pred))

In [137]:
#KNN with 1 neighbour
KNN(1,x_train, y_train,x_test,y_test)

Confusion Matrix of the given KNN classification with K = 1

[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  0  7  1  0  0  0  0  0  0]
 [ 0  0  0  8  0  2  0  0  0  1]
 [ 0  0  0  0 10  0  0  0  0  4]
 [ 0  1  0  1  1  4  0  0  0  0]
 [ 2  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  1]
 [ 0  0  1  0  0  0  0  0  1  0]
 [ 0  0  0  0  1  0  0  1  0  9]]

Accuracy of the above classification is  0.83


In [138]:
#KNN with 3 neighbour
KNN(3,x_train, y_train,x_test,y_test)

Confusion Matrix of the given KNN classification with K = 3

[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 1  1  6  0  0  0  0  0  0  0]
 [ 0  1  1  8  0  0  0  0  0  1]
 [ 0  0  0  0 10  0  0  0  0  4]
 [ 0  1  0  1  1  4  0  0  0  0]
 [ 2  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  1]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  2  0  9]]

Accuracy of the above classification is  0.83


In [139]:
#KNN with 5 neighbour
KNN(5,x_train, y_train,x_test,y_test)

Confusion Matrix of the given KNN classification with K = 5

[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  1  6  0  1  0  0  0  0  0]
 [ 0  1  1  8  0  0  0  0  0  1]
 [ 0  0  0  0 11  0  0  0  0  3]
 [ 0  1  0  1  1  4  0  0  0  0]
 [ 1  0  0  0  1  0  8  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  1]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  2  0  9]]

Accuracy of the above classification is  0.84


## Q2(CIFAR)

In [140]:
(x_train, y_train, x_test, y_test)=torch.load('cifar10.pt')

In [141]:
#creating histogram of the given input data and returning as new input data
def transform(dataset):
    new_data=[]
    for i in range(dataset.shape[0]):
        tmp=dataset[i].reshape((3,32,32))
        data=[]
        for j in range(3):
            pixels=tmp[j]
            pixels=pixels.reshape(32*32)
            count=[]
            for i in range(256):
                count.append(0)
            for i in range(1024):
                count[pixels[i]]+=1
            data+=count
        new_data.append(data)
    return np.asarray(new_data)

In [142]:
#creating histograms
x_train=transform(x_train)
x_test=transform(x_test)

In [143]:
x_train.shape

(1000, 768)

In [144]:
x_test.shape

(100, 768)

In [145]:
#KNN with 1 neighbour
KNN(1,x_train, y_train,x_test,y_test)

Confusion Matrix of the given KNN classification with K = 1

[[3 0 0 0 0 1 0 2 1 3]
 [1 1 1 1 1 0 0 0 0 1]
 [0 1 3 1 0 0 2 0 0 1]
 [0 0 1 1 1 0 4 0 0 3]
 [1 0 2 1 0 0 2 0 0 1]
 [0 1 1 0 0 0 2 2 0 2]
 [0 1 1 1 4 1 4 3 0 1]
 [0 1 2 0 1 1 2 0 2 2]
 [3 2 0 1 0 0 1 0 4 2]
 [0 1 3 1 3 0 0 2 0 1]]

Accuracy of the above classification is  0.17


In [146]:
#KNN with 3 neighbour
KNN(3,x_train, y_train,x_test,y_test)

Confusion Matrix of the given KNN classification with K = 3

[[4 1 1 0 1 1 1 1 0 0]
 [1 2 1 1 0 0 0 0 0 1]
 [1 2 3 0 0 0 1 0 0 1]
 [0 3 1 1 0 0 4 0 0 1]
 [2 0 2 1 1 0 1 0 0 0]
 [0 3 1 0 0 1 1 2 0 0]
 [0 1 2 4 2 3 3 1 0 0]
 [2 3 0 0 1 0 2 0 2 1]
 [4 2 1 0 0 0 0 1 3 2]
 [0 1 3 3 2 0 0 1 0 1]]

Accuracy of the above classification is  0.19


In [147]:
#KNN with 5 neighbour
KNN(5,x_train, y_train,x_test,y_test)

Confusion Matrix of the given KNN classification with K = 5

[[3 1 1 0 1 0 2 1 0 1]
 [1 2 1 1 0 0 0 0 0 1]
 [1 2 1 0 1 0 1 0 0 2]
 [0 3 1 1 0 0 4 0 0 1]
 [1 0 1 2 1 1 1 0 0 0]
 [0 2 1 0 1 1 1 1 0 1]
 [0 2 0 2 2 3 5 2 0 0]
 [1 2 1 0 1 1 2 0 1 2]
 [2 3 2 2 0 0 0 0 2 2]
 [0 0 1 4 1 0 2 2 0 1]]

Accuracy of the above classification is  0.17
